application: sexy-anime-reviews
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /add
  script: main.bottle
  login: admin
  secure: always
- url: .*
  script: main.bottle
  secure: always