runtime: python39
app_engine_apis: true

handlers:
- url: /add
  script: auto
  login: admin
  secure: always
- url: /edit/*
  script: auto
  login: admin
  secure: always
- url: .*
  script: auto
  secure: always