runtime: python27
threadsafe: yes

handlers:
- url: /add
  script: main.bottle
  login: admin
  secure: always
- url: /edit/*
  script: main.bottle
  login: admin
  secure: always
- url: .*
  script: main.bottle
  secure: always